### ISSUE TITLE
Got a CTD

### ISSUE THREAD

**Issue by festro** [Laavenx/MESWeaponBlacklistGui#1]
Got a CTD when clicking the blacklist button, crashlog is here

System.Func`11[System.String,System.UInt32,System.Boolean,System.Int64,System.String,System.Int32,System.Nullable`1[System.Single],VRage.Game.Entity.MyEntity,System.Boolean,System.Boolean,VRage.Game.Entity.MyEntity], instead it's: System.Func`12[System.String,System.UInt32,System.Boolean,System.Int64,System.String,System.Int32,System.Nullable`1[System.Single],VRage.Game.Entity.MyEntity,System.Boolean,System.Boolean,System.Int64,VRage.Game.Entity.MyEntity]
   at CoreSystems.Api.WcApi.AssignMethod[T](IReadOnlyDictionary`2 delegates, String name, T& field)
   at CoreSystems.Api.WcApi.ApiAssign(IReadOnlyDictionary`2 delegates, Boolean getWeaponDefinitions)
   at CoreSystems.Api.WcApi.HandleMessage(Object obj)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at CoreSystems.Api.ApiServer.HandleMessage(Object o)
   at Sandbox.ModAPI.MyAPIUtilities.SendModMessage(Int64 id, Object payload)
   at CoreSystems.Api.WcApi.Load(Action readyCallback, Boolean getWeaponDefinitions)
   at Blacklist.Gui.WeaponDialog.WeaponList()
   at Blacklist.Gui.WeaponDialog.ListWeapons()
   at Blacklist.Gui.WeaponDialog.CreateListBox()
   at Blacklist.Gui.WeaponDialog.RecreateControls(Boolean constructor)
   at Blacklist.Gui.WeaponDialog..ctor(String caption)
   at Blacklist.Logic.MainLogic.OnBlacklist()
   at Sandbox.Graphics.GUI.MyGuiControlButton.HandleInput()
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleControlsInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyGuiScreenBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Game.Gui.MyGuiScreenToolbarConfigBase.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2021-12-27 04:42:47.993 - Thread:   1 ->  Showing message
2021-12-27 04:42:49.798 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_199_025
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 437
PCUCount: 368242
IsHang: False
GCMemory: 3446
GCMemoryAllocated: 3446
HWAvailableMemory: 12637
ProcessPrivateMemory: 17698
AnalyticId: SE
================================== OFNI HSARC ==================================

2021-12-27 04:42:49.799 - Thread:   1 ->  Log Closed

**Comment by Laavenx** [comment]
I updated weaponcore api should be working now,

**Comment by festro** [comment]
Ok, thank you.

**Comment by festro** [comment]
I think the problem is still there as I still seem to be getting the same error when clicking the button. Is there something I need to do on my end?

**Comment by Laavenx** [comment]
I think weaponcore author updated his api again lol

**Comment by festro** [comment]
Yeah, I think his mods are the most updated; 80-90% of the time when SE mods get an update it's one of his.

**Comment by Forge12** [comment]
Same problem, Is there anyway we can get an update? or A Some guide on how we can fix it ourselves?
